version: "3.9"



x-healthcheck: &health-common
  healthcheck:
    start_period: 30s
    interval: 30s
    timeout: 10s
    retries: 5
  restart: always

services:

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - pg_data:/var/lib/postgresql/data
    <<: *health-common
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
    ports:
      - "5433:5432"

  pgadmin:
    profiles: # prefer dbeaver, so only run if profile set
      - pgadmin
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - 8080:80
    depends_on:    
      postgres:
        condition: service_healthy 

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
        - 8081:8978
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    environment:
      USER: db_admin
      PASSWORD: Password1
    # --add-host=host.docker.internal:IP -> Adds host name in the container's /etc/hosts file. 
    # This may be needed to access the database server deployed on the host machine
    # command:
      # "--add-host=host.docker.internal:${CB_LOCAL_HOST_ADDR}"
    depends_on:    
      postgres:
        condition: service_healthy 

  ingest-data:
    profiles:
      - init
    image: taxi_ingest:v001
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CSV_URL: "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-09.csv.gz"
      CSV_ZONE_URL: "https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv"    
      TABLE_NAME: "green_taxi_data"  
      # TABLE_NAME: "yellow_taxi_data"  
    entrypoint: ["/bin/sh", "-c", "--"]    
    command:
      - |
        echo "Ingest Data Python Pipeline"
        python ingest_data_green.py \
        --user=root \
        --password=root \
        --host=postgres  \
        --port=5432  \
        --db_name=ny_taxi  \
        --table_name=$${TABLE_NAME} \
        --csv_url=$${CSV_URL} \
        --csv_zone_url=$${CSV_ZONE_URL}
    depends_on:    
      postgres:
        condition: service_healthy 
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: "8G"
    #     reservations:
    #       cpus: "4"
    #       memory: "8G"




volumes:
  dbeaver_data:
  pg_data:
    # external: true
    # name: pg_data
